spring:
  datasource:
    url: jdbc:mysql://${port}/${db_name}
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${mailpwd}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          writetimeout: 5000
          starttls:
          enable: true
  auth-code-expiration-millis: 300000  # 1000 * 60 * 5  5분
  data:
    redis:
      host: localhost
      port: 6379
